Fix error introduced in r963409 causing "AttributeError: Broker instance has no attribute 'pid'"
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk/qpid@963737 13f79535-47bb-0310-9956-ffa450edef68