QPID-5318: HA tests fail sporadically with "AttributeError: 'NoneType' object has no attribute 'name'"
This was due to a race condition where a session was deleted while the QmfAgent
was looking it up.

git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@1540171 13f79535-47bb-0310-9956-ffa450edef68